### ISSUE TITLE
trainset and initial netconstruction notebook for kymobutler and segbutler

### ISSUE THREAD

**Issue by alihashmiii** [MaxJakobs/KymoButler#1]
Hi Max,

It is not an issue but did not know where else to contact you. It would be great if  you can provide the trainset and initial netconstruction notebook for kymobutler and segbutler.

Ali

**Comment by MaxJakobs** [comment]
Hey Ali,
Nice to e-meet another AI Mathematica user!! Hope you enjoying the beauty of it like I did. Unfortunately, both the training sets for segbutler and KymoButler contain unpublished data from friends & colleagues so I can not share those with you. For cells & nuclei there are quite a few public datasets though (let me know if you want some pointers).

Nevertheless, I uploaded the net refs for the Kymobuter neural network here so you can see how they were put together. The segbutler one is the same except that it uses the Cellpose algorithm to reconstruct the image after. I will upload those to the segbutler git.
